<!-- Copyright (c) 2026 MikeRust contributors. Licensed under AGPL-3.0-only. -->
<!--
  Chat-files shortcut popover.

  Surfaces every document seen by the current chat — uploaded by the
  user, generated by a tool (today docx/xlsx from generate_docx),
  rejected via the accept/reject flow — in a single list so the user
  can find a generated docx after the chat scrolled past, or jump back
  to a document they vetoed. Click a row to open it in the existing
  doc-viewer side panel (same as the ChatSteps doc card).

  Source of truth: `GET /chat/:id/documents`. Both the composer upload
  flow and the `generate_docx` tool set `documents.chat_id`, so a single
  backend query enumerates everything the chat has ever touched, with
  decision state in the same row (no N+1). Walking the in-memory
  `chatStore.messages` array is not enough — `messages.files` is not
  echoed back by GET /chat/:id/messages, so uploads disappear on chat
  reload.

  The "uploaded vs generated" distinction is still derived locally by
  intersecting docIds with assistant `steps` of kind 'doc' (the rehydrated
  doc_created events). Anything not in that set is treated as uploaded.
-->
<script lang="ts">
  import { docViewer } from '$lib/stores/doc-viewer.svelte'
  import { chatStore } from '$lib/stores/chat.svelte'
  import { chatApi } from '$lib/api/chat'
  import { i18n } from '$lib/stores/i18n.svelte'
  import { fileIconColor } from '$lib/utils/file-icon'
  import Spinner from '$lib/components/ui/Spinner.svelte'
  import { FileText, X } from 'lucide-svelte'

  interface Props {
    open: boolean
    onclose?: () => void
  }

  let { open = $bindable(false), onclose }: Props = $props()

  type Origin = 'uploaded' | 'generated'
  type Decision = 'accepted' | 'rejected'

  interface Row {
    docId: string
    filename: string
    origin: Origin
    decision: Decision
  }

  let rows = $state<Row[]>([])
  let loading = $state(false)

  /** docIds known to be tool-generated (assistant doc_created steps).
   *  Anything else returned by the backend chat-documents endpoint is
   *  classified as an uploaded attachment. */
  function generatedDocIds(): Set<string> {
    const out = new Set<string>()
    for (const m of chatStore.messages) {
      if (m.role !== 'assistant' || !m.steps) continue
      for (const s of m.steps) {
        if (s.kind === 'doc' && s.documentId) out.add(s.documentId)
      }
    }
    return out
  }

  // Re-fetch the chat's documents every time the panel opens. Both
  // the set (a new generate or upload) and the decision state (a fresh
  // reject) can change between opens, and the call is a single SQL
  // SELECT on the backend — cheap enough to re-run without caching.
  $effect(() => {
    if (!open) return
    const chatId = chatStore.activeId
    if (!chatId) {
      // Brand-new unsaved chat: nothing exists server-side yet.
      rows = []
      return
    }
    loading = true
    const generated = generatedDocIds()
    chatApi
      .documents(chatId)
      .then((res) => {
        if (!open) return // raced a close
        rows = res.documents.map((d) => ({
          docId: d.id,
          filename: d.filename,
          origin: generated.has(d.id) ? 'generated' : 'uploaded',
          decision: d.decision,
        }))
      })
      .catch(() => {
        if (open) rows = []
      })
      .finally(() => {
        loading = false
      })
  })

  function close() {
    open = false
    onclose?.()
  }

  function pick(r: Row) {
    docViewer.openDocument(r.docId, r.filename)
    close()
  }

  function originLabel(o: Origin): string {
    return o === 'uploaded'
      ? i18n.t('ChatFiles.originUploaded')
      : i18n.t('ChatFiles.originGenerated')
  }
</script>

{#if open}
  <!-- Backdrop closes the popover, but it stays transparent — this is
       a lightweight pop-up anchored above the composer, not a modal. -->
  <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-30" onclick={close}></div>

  <div
    class="absolute bottom-full mb-1.5 left-0 z-40
           w-[min(28rem,calc(100vw-3rem))] max-h-[60vh]
           rounded-(--radius-md) border border-(--color-surface-200)
           bg-(--color-surface-0) shadow-(--shadow-modal)
           flex flex-col overflow-hidden"
    role="dialog"
    aria-label={i18n.t('ChatFiles.title')}
  >
    <header
      class="px-3.5 py-2.5 border-b border-(--color-surface-100)
             flex items-center justify-between gap-3 shrink-0"
    >
      <h2 class="text-sm font-semibold text-(--color-text-primary)">
        {i18n.t('ChatFiles.title')}
      </h2>
      <button
        type="button"
        aria-label={i18n.t('Common.close')}
        onclick={close}
        class="inline-flex h-6 w-6 items-center justify-center rounded-(--radius-md)
               text-(--color-text-secondary) hover:bg-(--color-hover-bg)"
      >
        <X size={14} />
      </button>
    </header>

    <div class="overflow-y-auto flex-1 min-h-0">
      {#if rows.length === 0}
        <p class="px-3.5 py-6 text-xs text-(--color-text-secondary) text-center">
          {i18n.t('ChatFiles.empty')}
        </p>
      {:else}
        <ul class="py-1">
          {#each rows as r (r.docId)}
            {@const isRejected = r.decision === 'rejected'}
            <li>
              <button
                type="button"
                onclick={() => pick(r)}
                class="w-full flex items-center gap-2.5 px-3.5 py-2 text-left
                       hover:bg-(--color-hover-bg) focus:outline-none
                       focus-visible:bg-(--color-hover-bg)"
              >
                <FileText size={16} class="{fileIconColor(r.filename)} shrink-0" />
                <span
                  class="flex-1 min-w-0 truncate text-sm
                         text-(--color-text-primary)
                         {isRejected ? 'line-through text-(--color-text-secondary)' : ''}"
                  title={r.filename}
                >
                  {r.filename}
                </span>
                <span
                  class="text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded-(--radius-sm)
                         {r.origin === 'generated'
                           ? 'bg-(--color-brand-50) text-(--color-brand-700)'
                           : 'bg-(--color-surface-100) text-(--color-text-secondary)'}"
                >
                  {originLabel(r.origin)}
                </span>
                {#if isRejected}
                  <span
                    class="text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded-(--radius-sm)
                           bg-(--color-danger-500) text-white"
                  >
                    {i18n.t('DocViewer.decision.rejectedBadge')}
                  </span>
                {/if}
              </button>
            </li>
          {/each}
        </ul>
      {/if}
    </div>

    {#if loading}
      <footer
        class="px-3.5 py-2 border-t border-(--color-surface-100)
               text-[11px] text-(--color-text-secondary)
               flex items-center gap-2 shrink-0"
      >
        <Spinner size="sm" />
        <span>{i18n.t('ChatFiles.hydrating')}</span>
      </footer>
    {/if}
  </div>
{/if}
